### PR TITLE
Update Compadre description

### PR DESCRIPTION
**Pull request by kuberry**
Reworked the Compadre description to be more terse and drop lots of details about options.

### CODE REVIEW

**Comment by kuberry** [comment]
Reworked the Compadre description to be more terse and drop lots of details about options.

**Comment by kuberry** [comment]
@mperego Does this read well to you?

**Review by mayrmt — APPROVED** [review]

**Comment by mayrmt** [comment]
@kuberry, thanks for making those changes!

**Review by mperego — APPROVED** [review]
Looks good. Thanks!

**Comment by mayrmt** [comment]
@kuberry @mperego, can I merge this?

**Comment by kuberry** [comment]
> @kuberry, thanks for making those changes!

Sure! Glad that it is closer to what you were looking for.

**Pull request merged**
