### PR TITLE
Add panzer and thyra sections

### PR DESCRIPTION
**Pull request by rppawlo**

### CODE REVIEW

**Comment by rppawlo** [comment]
@bartlettroscoe - I started a draft of the thyra section. Needs lots of cleanup. Can you look at this and push up any changes here?

**Review by mperego — APPROVED** [review]
Looks good to me.

**Comment by mperego** [comment]
@rppawlo can we merge this? I wanted to work a bit on the organization of the Discretization and Analysis packages and it's easier to work from the main.

**Comment by bartlettroscoe** [comment]
I am okay merging to help @mperego and I will open a new PR for any changes to Thyra section.

**Comment by mperego** [comment]
Thanks @bartlettroscoe and @rppawlo !

**Comment by searhein** [comment]
Thanks @bartlettroscoe, @mperego, and @rppawlo!

**Pull request merged**
