### PR TITLE
Kokkos Kernels: initial draft of the description of the library

### PR DESCRIPTION
**Pull request by lucbv**

### CODE REVIEW

**Comment by lucbv** [comment]
@srajama1 do you want to have a look at this and give some feedback?

**Comment by kliegeois** [comment]
@lucbv could you add some references for the interested reader to continue the lecture?

I would add:

```
@article{trott2021kokkos,
  title={The Kokkos ecosystem: Comprehensive performance portability for high performance computing},
  author={Trott, Christian and Berger-Vergiat, Luc and Poliakoff, David and Rajamanickam, Sivasankaran and Lebrun-Grandie, Damien and Madsen, Jonathan and Al Awar, Nader and Gligoric, Milos and Shipman, Galen and Womeldorff, Geoff},
  journal={Computing in Science \& Engineering},
  volume={23},
  number={5},
  pages={10--18},
  year={2021},
  publisher={IEEE}
}

@article{rajamanickam2021kokkos,
  title={Kokkos kernels: Performance portable sparse/dense linear algebra and graph kernels},
  author={Rajamanickam, Sivasankaran and Acer, Seher and Berger-Vergiat, Luc and Dang, Vinh and Ellingwood, Nathan and Harvey, Evan and Kelley, Brian and Trott, Christian R and Wilke, Jeremiah and Yamazaki, Ichitaro},
  journal={arXiv preprint arXiv:2103.11991},
  year={2021}
}

@article{liegeois2023performance,
  title={Performance Portable Batched Sparse Linear Solvers},
  author={Liegeois, Kim and Rajamanickam, Sivasankaran and Berger-Vergiat, Luc},
  journal={IEEE Transactions on Parallel and Distributed Systems},
  volume={34},
  number={5},
  pages={1524--1535},
  year={2023},
  publisher={IEEE}
}

@inproceedings{kelley2022parallel,
  title={Parallel, Portable Algorithms for Distance-2 Maximal Independent Set and Graph Coarsening},
  author={Kelley, Brian and Rajamanickam, Sivasankaran},
  booktitle={2022 IEEE International Parallel and Distributed Processing Symposium (IPDPS)},
  pages={280--290},
  year={2022},
  organization={IEEE}
}

@inproceedings{kim2017designing,
  title={Designing vector-friendly compact BLAS and LAPACK kernels},
  author={Kim, Kyungjoo and Costa, Timothy B and Deveci, Mehmet and Bradley, Andrew M and Hammond, Simon D and Guney, Murat E and Knepper, Sarah and Story, Shane and Rajamanickam, Sivasankaran},
  booktitle={Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis},
  pages={1--12},
  year={2017}
}

@article{deveci2018multithreaded,
  title={Multithreaded sparse matrix-matrix multiplication for many-core and GPU architectures},
  author={Deveci, Mehmet and Trott, Christian and Rajamanickam, Sivasankaran},
  journal={Parallel Computing},
  volume={78},
  pages={33--46},
  year={2018},
  publisher={Elsevier}
}

@inproceedings{wolf2017fast,
  title={Fast linear algebra-based triangle counting with kokkoskernels},
  author={Wolf, Michael M and Deveci, Mehmet and Berry, Jonathan W and Hammond, Simon D and Rajamanickam, Sivasankaran},
  booktitle={2017 IEEE High Performance Extreme Computing Conference (HPEC)},
  pages={1--7},
  year={2017},
  organization={IEEE}
}

```

**Review by srajama1 — APPROVED** [review]

**Comment by srajama1** [comment]
Can you please add the references as well?

**Comment by lucbv** [comment]
Okay, I added the references and cited them through the text.

**Comment by lucbv** [comment]
There are a lot of issues with other references when running bibtex but I think the new ones are compiling cleanly so that's something...

**Comment by kliegeois** [comment]
Thanks @lucbv !

**Pull request merged**
