### PR TITLE
Edits to Discretizations product

### PR DESCRIPTION
**Pull request by mperego**
Adding Nate Roberts and Paul Kuberry as authors.
Very preliminary content for the Discretization product (from the website).

### CODE REVIEW

**Comment by mperego** [comment]
@srajama1 @rppawlo , what's the policy for snapshot packages? I see that you have a section on `KokkosKernels` but not on `Kokkos`. 
There are a couple of snapshot packages in the Discretizations product, `MiniTensor` and `Percept`, that are "new" but already in maintenance mode and they run only serially. Should we describe them in the paper? Also, what about `STK` and `Krino`?

**Comment by srajama1** [comment]
@mperego Couple of things. I hesitate to add folks' name who hasn't read the paper or contributed to writing. We could add them in acknowledgements if needed. We could also request them to actually work on the paper right away.

If packages are in maintenance mode, I suggest we don't add it. Snapshotted packages like STK and Krino can be mentioned  in a sentence and we can add a reference (if any).

**Comment by mperego** [comment]
> @mperego Couple of things. I hesitate to add folks' name who hasn't read the paper or contributed to writing. We could add them in acknowledgements if needed. We could also request them to actually work on the paper right away.
> 
> If packages are in maintenance mode, I suggest we don't add it. Snapshotted packages like STK and Krino can be mentioned in a sentence and we can add a reference (if any).

OK, thanks for the feedback. As for adding authors, I'm sure that Nate and Paul will contribute to the paper. Paul is the developer of one of the packages and he has been very active on developing a Spack build. Nate has made major contributions to intrepid2 and the will add content to the paper. Let me work on mergin this PR today or tomorrow and then I'll ping them to work on the description of the discretization packages they work on.

Sounds good to me to mention Snapshotted packages in a few sentences.

**Comment by mperego** [comment]
@srajama1 I didn't add new authors for now, but I want to invite Nate and Paul to edit the paper and they'll add themselves as authors as they contribute to the paper

**Review by rppawlo — APPROVED** [review]

**Comment by srajama1** [comment]
Thanks @mperego ! Sounds good to me.

**Pull request merged**
