### PR TITLE
Add a first draft of the description of Belos

### PR DESCRIPTION
**Pull request by mayrmt**

### CODE REVIEW

**Comment by mayrmt** [comment]
@jhux2 @srajama1 I put together a first draft of a description of Belos. Please review it carefully and feel free to remove/add text, as I might have missed or overstated some features.

**Comment by mayrmt** [comment]
@jennloe

**Comment by jennloe** [comment]
Can we add hkthorn to the paper?  She was wanting to work on the Belos section.  I have been out on leave and haven’t had time to work on it, unfortunately.
Jennifer

From: Matthias Mayr ***@***.***>
Date: Monday, June 5, 2023 at 2:19 AM
To: searhein/trilinos-paper ***@***.***>
Cc: Loe, Jennifer ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [searhein/trilinos-paper] Add a first draft of the description of Belos (PR #24)

@jennloe<https://github.com/jennloe>

**Comment by jennloe** [comment]
I was working on the Belos section last week during the SIAM OPT23 conference, so if you want to include me in this issue you can.

Thanks,
Heidi

From: Loe, Jennifer ***@***.***>
Date: Tuesday, June 6, 2023 at 4:48 PM
To: searhein/trilinos-paper ***@***.***>, Alexander Heinlein ***@***.***>, Thornquist, Heidi K ***@***.***>
Cc: Rajamanickam, Sivasankaran ***@***.***>
Subject: Re: [EXTERNAL] Re: [searhein/trilinos-paper] Add a first draft of the description of Belos (PR #24)
Can we add hkthorn to the paper?  She was wanting to work on the Belos section.  I have been out on leave and haven’t had time to work on it, unfortunately.
Jennifer

From: Matthias Mayr ***@***.***>
Date: Monday, June 5, 2023 at 2:19 AM
To: searhein/trilinos-paper ***@***.***>
Cc: Loe, Jennifer ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [searhein/trilinos-paper] Add a first draft of the description of Belos (PR #24)

@jennloe<https://github.com/jennloe>

**Comment by searhein** [comment]
I just added @hkthorn to the repository.

**Comment by hkthorn** [comment]
@searhein @jennloe I've updated the Belos section, building off Matthias' work.

**Comment by hkthorn** [comment]
I went ahead an added a brief discussion of Anasazi on the same branch.  Hopefully that is okay.  :)

**Comment by searhein** [comment]
@hkthorn Great. Thank you!

**Pull request merged**
